---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: zfs
provisioner: creamfinance.com/zfs
reclaimPolicy: Delete
parameters:
  parentDataset: "zpool1"
  shareOptions: "rw=@172.29.49.0/8"
  serverHostname: "172.29.49.1"
  overProvision: "false"
